### PR TITLE
Allowing to process base64 images

### PR DESCRIPTION
**Pull request by rgolea**
Hi there, I had an issue while displaying base64 created images whenever I sent an email to gmail. This should fix that issue. Please tell me whenever you merge it to master.

### CODE REVIEW

**Comment by NicolasRitouet** [comment]
LGTM, but @ericfong is the owner of this module and he's currently on vacation.
When he's back, he's take care of this.
Thanks for your patience

**Comment by ericfong** [comment]
I am so sorry to be late to review this.

And I am not sure it is right to make this is default action to add base64 plugin.
Can we have a switch to opt-in this feature?

By the way, I use embedded image instead of base64
https://github.com/andris9/Nodemailer#using-embedded-images

**Comment by rgolea** [comment]
I know, we could try to use it in options, but the problem is that, for example, in my case, I use a generated qr that I use for a 2 factor authentication. I do not want to generate any file nor embed it since it's safer to just push a base64 encrypted auto-generated image. If you really want to, we could add something for base64 to be clickable images.

**Comment by rgolea** [comment]
I modified it to be optional, but as you can see, I, personally, still need it as base64. Thank you for everything.

**Comment by ericfong** [comment]
Thx. I just think not everyone share same use case. So I try to keep default as minimum

**Comment by ericfong** [comment]
published. Thx

**Comment by rgolea** [comment]
Sure! I didn't think of that but I get the point. Thanks a lot.

**Pull request merged**
